spring:
  application:
    name: rokdemo

  thymeleaf:
    cache: false

  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html

jwt:
  secret: your-256-bit-secret-key-change-this-in-production-must-be-at-least-256-bits
  expiration: 86400000 # 24시간 (밀리초)

server:
  port: 8087
